In [1]:
import pandas as pd

In [2]:
from functions import read_data, clean_data, clean_table3

In [3]:
url1 = r"data/mental_health_and_technology_usage_2024.csv"
df1 = read_data(url1)  #lee el archivo csv
df1 = clean_data(df1)  #cambia los nombres de las columnas a minusculas y reemplaza espacios en blancos por_
df1.head()

,user_id,age,gender,technology_usage_hours,social_media_usage_hours,gaming_hours,screen_time_hours,mental_health_status,stress_level,sleep_hours,physical_activity_hours,support_systems_access,work_environment_impact,online_support_usage
0,USER-00001,23,Female,6.57,6.00,0.68,12.36,Good,Low,8.01,6.71,No,Negative,Yes
1,USER-00002,21,Male,3.01,2.57,3.74,7.61,Poor,High,7.28,5.88,Yes,Positive,No
2,USER-00003,51,Male,3.04,6.14,1.26,3.16,Fair,High,8.04,9.81,No,Negative,No
3,USER-00004,25,Female,3.84,4.48,2.59,13.08,Excellent,Medium,5.62,5.28,Yes,Negative,Yes
4,USER-00005,53,Male,1.20,0.56,0.29,12.63,Good,Low,5.55,4.00,No,Positive,Yes

In [4]:
url2 = r"data/dummy_data.csv"
df2 = read_data(url2)
df2 = clean_data(df2)
df2.head()

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,ishomeowner,owns_car
0,56,male,3,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774,True,False,False
1,46,female,2,Facebook,Travel,United Kingdom,Urban,Student,10564,True,True,True
2,32,male,8,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258,False,False,False
3,60,non-binary,5,Instagram,Travel,United Kingdom,Urban,Student,12500,False,True,False
4,25,male,1,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566,False,True,True

In [5]:
url3 = r"data/smmh.csv"
df3 = read_data(url3)
df3 = clean_data(df3)

df3 = clean_table3(df3) 

df3.head()

,timestamp,age,gender,relationship_status,4._occupation_status,5._what_type_of_organizations_are_you_affiliated_with?,6._do_you_use_social_media?,platform,8._what_is_the_average_time_you_spend_on_social_media_every_day?,9._how_often_do_you_find_yourself_using_social_media_without_a_specific_purpose?,...,11._do_you_feel_restless_if_you_haven't_used_social_media_in_a_while?,"12._on_a_scale_of_1_to_5,_how_easily_distracted_are_you?","13._on_a_scale_of_1_to_5,_how_much_are_you_bothered_by_worries?",14._do_you_find_it_difficult_to_concentrate_on_things?,"15._on_a_scale_of_1-5,_how_often_do_you_compare_yourself_to_other_successful_people_through_the_use_of_social_media?","16._following_the_previous_question,_how_do_you_feel_about_these_comparisons,_generally_speaking?",17._how_often_do_you_look_to_seek_validation_from_features_of_social_media?,18._how_often_do_you_feel_depressed_or_down?,"19._on_a_scale_of_1_to_5,_how_frequently_does_your_interest_in_daily_activities_fluctuate?","20._on_a_scale_of_1_to_5,_how_often_do_you_face_issues_regarding_sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1